FROM python:3.9-bullseye

RUN apt-get update && apt-get install -y less curl sudo
RUN pip install -U pip
COPY ./docker/python/requirements.txt ./docker/python/requirements.dev.txt .
RUN pip install --no-cache-dir -r requirements.txt -r requirements.dev.txt

WORKDIR /var/app
# listen 8000 port...
CMD ["uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8080"]
