services:
  python:
    build:
      context: ./
      dockerfile: ./docker/python/Dockerfile.dev
    image: codingwork_sqlalchemy_python
    ports:
      - "8080:8080"
    volumes:
      - ./app:/var/app
    stdin_open: true
    tty: true
    env_file:
      - app/.env
    depends_on:
      - mysql

  mysql:
    build:
      context: ./
      dockerfile: ./docker/mysql/Dockerfile
    image: codingwork_sqlalchemy_mysql
    platform: linux/x86_64
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d:delegated
      - ./docker/mysql/data/mysql:/etc/mysql/conf.d:delegated
    stdin_open: true
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: secret
      TZ: "Asia/Tokyo"
