services:
  python:
    build:
      context: ./
      dockerfile: ./docker/python/Dockerfile.dev
    image: codingwork_sqlalchemy_python
    ports:
      - "8080:8080"
    volumes:
      - ./app:/var/app
    stdin_open: true
    tty: true
    env_file:
      - app/.env
    depends_on:
      mysql:
        condition: service_healthy
    command: /bin/bash -c "uvicorn main:app --reload --host 0.0.0.0 --port 8080"

  mysql:
    build:
      context: ./
      dockerfile: ./docker/mysql/Dockerfile
    image: codingwork_sqlalchemy_mysql
    platform: linux/x86_64
    ports:
      - "3306:3306"
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_bin
    healthcheck:
      test: ["CMD", "mysqladmin", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 15s
    volumes:
      - ./docker/mysql/initdb.d:/docker-entrypoint-initdb.d:delegated
      - ./docker/mysql/data/mysql:/etc/mysql/conf.d:delegated
    stdin_open: true
    tty: true
    env_file:
      - app/.env
    environment:
      TZ: "Asia/Tokyo"
